import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "TO DO LIST",
    description: "Generated by create next app",
};

interface IProps {
    children: React.ReactNode;
}

export default function RootLayout({ children }: IProps) {
    return (
        <html lang="en" style={{ colorScheme: "dark" }}>
            <body className={inter.className}>
                <main className="max-w-xl min-h-screen mx-auto p-4">
                    <header>
                        <h1 className="text-3xl font-bold text-center w-full">
                            🖊️ TO DO LIST 🗒️
                        </h1>
                    </header>
                    <section>{children}</section>
                </main>
            </body>
        </html>
    );
}
